/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ganek-logo-3d.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function GanekLogo(props) {
  const { nodes, materials } = useGLTF("/models/ganek-logo-3d-2.glb");

  const ref = useRef();

  useFrame((state, delta) => (ref.current.rotation.y -= delta / 5));
  useFrame(({ clock, mouse, delta }) => {
    ref.current.rotation.x = Math.sin(clock.getElapsedTime()) * 0.1;
    // ref.current.rotation.y -= delta / 5;
    // ref.current.rotation.y = THREE.MathUtils.lerp(
    //   ref.current.rotation.y,
    //   mouse.x * Math.PI,
    //   0.01
    // );

    ref.current.rotation.y = THREE.MathUtils.lerp(
      ref.current.rotation.y,
      ref.current.rotation.y + mouse.x * Math.PI,
      0.01
    );
  });

  return (
    <group {...props} dispose={null}>
      {/* <mesh
        ref={ref}
        geometry={nodes.font1.geometry}
        material={nodes.font1.material}
      /> */}
      {/* <mesh geometry={nodes.font1.geometry} ref={ref}>
        <meshPhysicalMaterial
          clearcoat={0}
          clearcoatRoughness={0}
          roughness={0}
          metalness={1}
        />
      </mesh> */}
      <mesh geometry={nodes.font1.geometry} ref={ref}>
        <meshPhysicalMaterial
          // ref={matRef}
          // color={"#b1fc05"}
          color={"white"}
          roughness={0.0}
          metalness={0.0}
          emissive={"white"}
          emissiveIntensity={0.1}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/ganek-logo-3d.glb");
